export const PORTFOLIO_ACTIONS = {
  // Application Status
  SET_LOADING: "SET_LOADING",
  SET_READY: "SET_READY",
  SET_SERVER_DOWN: "SET_SERVER_DOWN",
  SET_MAINTENANCE: "SET_MAINTENANCE",

  // Portfolio Data
  SET_CONFIGURATION: "SET_CONFIGURATION",
  SET_STATISTICS: "SET_STATISTICS",
  SET_SERVICES: "SET_SERVICES",
  SET_TECHNOLOGIES: "SET_TECHNOLOGIES",
  SET_FAQS: "SET_FAQS",


  SET_HOME_PROJECTS: "SET_HOME_PROJECTS",
  SET_FEATURED_PROJECTS: "SET_FEATURED_PROJECTS",

  // Reset
  RESET: "RESET",
};