export const PORTFOLIO_ACTIONS = {
  // Application Status
  SET_LOADING: "SET_LOADING",
  SET_READY: "SET_READY",
  SET_SERVER_DOWN: "SET_SERVER_DOWN",
  SET_MAINTENANCE: "SET_MAINTENANCE",

  // Portfolio Data
  SET_ABOUT: "SET_ABOUT",
  SET_SERVICES: "SET_SERVICES",
  SET_PROJECTS: "SET_PROJECTS",
  SET_RESUME: "SET_RESUME",
  SET_SKILLS: "SET_SKILLS",
  SET_STATISTICS: "SET_STATISTICS",
  SET_CERTIFICATES: "SET_CERTIFICATES",

  // Reset
  RESET: "RESET",
};