# Generated by Django 6.0.5 on 2026-07-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_description_service_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='technology',
            name='color',
            field=models.CharField(default=123, help_text='Hex color code, e.g. #61DAFB', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.CharField(default=111, help_text='React Icon name, e.g. SiReact', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
