# Generated by Django 6.0.5 on 2026-07-11 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_technology_options_technology_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Technology Type',
                'verbose_name_plural': 'Technology Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='technology',
            name='category',
        ),
        migrations.AddField(
            model_name='technology',
            name='tech_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio.technologytype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
