# Generated by Django 6.0.5 on 2026-07-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ('-created_at',), 'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenance'},
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='button_url',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Enable this maintenance schedule.'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
