# Generated by Django 6.0.5 on 2026-07-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ('display_order', 'title'), 'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='portfolio_s_display_229172_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='portfolio_s_is_acti_ab410e_idx',
        ),
        migrations.AddField(
            model_name='statistic',
            name='description',
            field=models.TextField(default=1, help_text='Short description displayed below the title.', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Controls the display order on the homepage.'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(help_text='Lucide React icon name. Example: FolderGit2', max_length=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='title',
            field=models.CharField(help_text='Example: Projects Completed', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value',
            field=models.CharField(help_text='Example: 25+, 100+, 99%', max_length=50),
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='color',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='subtitle',
        ),
    ]
