# Generated by Django 6.0.5 on 2026-07-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_statistic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(help_text='Website name. Example: Deepak Raikwar', max_length=100)),
                ('site_title', models.CharField(help_text='Main website title.', max_length=200)),
                ('site_tagline', models.CharField(blank=True, help_text='Short tagline.', max_length=250)),
                ('short_description', models.TextField(help_text='Short portfolio description.', max_length=500)),
                ('site_url', models.URLField(help_text='Frontend URL.')),
                ('backend_url', models.URLField(help_text='Backend URL.')),
                ('logo', models.ImageField(help_text='Website logo.', upload_to='portfolio/configuration/logo/')),
                ('favicon', models.ImageField(blank=True, help_text='Website favicon.', null=True, upload_to='portfolio/configuration/favicon/')),
                ('resume', models.FileField(blank=True, help_text='Resume PDF.', null=True, upload_to='portfolio/configuration/resume/')),
                ('email', models.EmailField(help_text='Public email.', max_length=254)),
                ('email_icon', models.CharField(default='Mail', help_text='Lucide icon name.', max_length=100)),
                ('mobile_number', models.CharField(help_text='Public mobile number.', max_length=20)),
                ('mobile_icon', models.CharField(default='Phone', help_text='Lucide icon name.', max_length=100)),
                ('country', models.CharField(help_text='Country.', max_length=100)),
                ('country_icon', models.CharField(default='MapPinned', help_text='Lucide icon name.', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Personal website.')),
                ('website_icon', models.CharField(default='Globe', help_text='Lucide icon name.', max_length=100)),
                ('github_url', models.URLField(blank=True, help_text='GitHub URL.')),
                ('github_icon', models.CharField(default='Github', help_text='Lucide icon name.', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn URL.')),
                ('linkedin_icon', models.CharField(default='Linkedin', help_text='Lucide icon name.', max_length=100)),
                ('leetcode_url', models.URLField(blank=True, help_text='LeetCode URL.')),
                ('leetcode_icon', models.CharField(default='Code2', help_text='Lucide icon name.', max_length=100)),
                ('hackerrank_url', models.URLField(blank=True, help_text='HackerRank URL.')),
                ('hackerrank_icon', models.CharField(default='Code', help_text='Lucide icon name.', max_length=100)),
                ('codeforces_url', models.URLField(blank=True, help_text='Codeforces URL.')),
                ('codeforces_icon', models.CharField(default='Terminal', help_text='Lucide icon name.', max_length=100)),
                ('codechef_url', models.URLField(blank=True, help_text='CodeChef URL.')),
                ('codechef_icon', models.CharField(default='ChefHat', help_text='Lucide icon name.', max_length=100)),
                ('twitter_url', models.URLField(blank=True, help_text='X/Twitter URL.')),
                ('twitter_icon', models.CharField(default='Twitter', help_text='Lucide icon name.', max_length=100)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram URL.')),
                ('instagram_icon', models.CharField(default='Instagram', help_text='Lucide icon name.', max_length=100)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube URL.')),
                ('youtube_icon', models.CharField(default='Youtube', help_text='Lucide icon name.', max_length=100)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title.', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description.')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated SEO keywords.', max_length=500)),
                ('copyright_text', models.CharField(blank=True, help_text='Footer copyright.', max_length=300)),
                ('footer_text', models.CharField(blank=True, help_text='Footer text.', max_length=300)),
                ('is_resume_public', models.BooleanField(default=True, help_text='Allow resume download.')),
                ('is_email_public', models.BooleanField(default=True, help_text='Show email publicly.')),
                ('is_mobile_public', models.BooleanField(default=True, help_text='Show mobile publicly.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable configuration.')),
            ],
            options={
                'verbose_name': 'Portfolio Configuration',
                'verbose_name_plural': 'Portfolio Configuration',
                'db_table': 'portfolio_configuration',
            },
        ),
    ]
