# Generated by Django 6.0.5 on 2026-07-13 14:20

import apps.portfolio.models.project
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_portfolioconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name of the project category.', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated unique slug.', unique=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name (Lucide, FontAwesome, etc.).', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Controls the display order of categories.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this category.')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('display_order', 'title'), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ('id',), 'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, help_text='Client or organization.', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='Demo video URL.'),
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=1, help_text='Controls project ordering.'),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, help_text='Example: 3 Months', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='figma_url',
            field=models.URLField(blank=True, help_text='Figma design URL.'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Hide project without deleting.'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('CLIENT', 'Client'), ('OPEN_SOURCE', 'Open Source'), ('COLLEGE', 'College')], default='PERSONAL', help_text='Project type.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='project_year',
            field=models.PositiveIntegerField(default=2026, help_text='Project completion year.'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default=1, help_text='Short summary for cards.', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Show project on landing page.'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('DEVELOPMENT', 'In Development'), ('MAINTENANCE', 'Maintenance'), ('ARCHIVED', 'Archived')], default='LIVE', help_text='Current project status.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(help_text='Technologies used in this project.', related_name='projects', to='portfolio.technology'),
        ),
        migrations.AlterField(
            model_name='portfolioconfiguration',
            name='logo',
            field=models.ImageField(blank=True, help_text='Website logo.', null=True, upload_to='portfolio/configuration/logo/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Complete project description.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Highlight this project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Live demo URL.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatically generated from title.', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(help_text='Main thumbnail image.', upload_to='portfolio/projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Project title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique project identifier.', unique=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Additional project image.', upload_to=apps.portfolio.models.project.project_image_upload_path),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(help_text='Parent project.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(help_text='Project category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectcategory'),
        ),
    ]
